import { db } from '@/db';
import { districts } from '@/db/schema';

async function main() {
    const timestamp = new Date().toISOString();
    
    const sampleDistricts = [
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'AGRA',
            districtNameHindi: 'आगरा',
            districtCode: '09-01',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'ALIGARH',
            districtNameHindi: 'अलीगढ़',
            districtCode: '09-02',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'AMBEDKAR NAGAR',
            districtNameHindi: 'अम्बेडकर नगर',
            districtCode: '09-03',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'AMETHI',
            districtNameHindi: 'अमेठी',
            districtCode: '09-04',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'AMROHA',
            districtNameHindi: 'अमरोहा',
            districtCode: '09-05',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'AURAIYA',
            districtNameHindi: 'औरैया',
            districtCode: '09-06',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'AZAMGARH',
            districtNameHindi: 'आज़मगढ़',
            districtCode: '09-07',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'BAGHPAT',
            districtNameHindi: 'बागपत',
            districtCode: '09-08',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'BAHRAICH',
            districtNameHindi: 'बहराइच',
            districtCode: '09-09',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'BALLIA',
            districtNameHindi: 'बलिया',
            districtCode: '09-10',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'BALRAMPUR',
            districtNameHindi: 'बलरामपुर',
            districtCode: '09-11',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'BANDA',
            districtNameHindi: 'बांदा',
            districtCode: '09-12',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'BARABANKI',
            districtNameHindi: 'बाराबंकी',
            districtCode: '09-13',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'BAREILLY',
            districtNameHindi: 'बरेली',
            districtCode: '09-14',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'BASTI',
            districtNameHindi: 'बस्ती',
            districtCode: '09-15',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'BHADOHI',
            districtNameHindi: 'भदोही',
            districtCode: '09-16',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'BIJNOR',
            districtNameHindi: 'बिजनौर',
            districtCode: '09-17',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'BUDAUN',
            districtNameHindi: 'बदायूं',
            districtCode: '09-18',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'BULANDSHAHR',
            districtNameHindi: 'बुलंदशहर',
            districtCode: '09-19',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'CHANDAULI',
            districtNameHindi: 'चंदौली',
            districtCode: '09-20',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'CHITRAKOOT',
            districtNameHindi: 'चित्रकूट',
            districtCode: '09-21',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'DEORIA',
            districtNameHindi: 'देवरिया',
            districtCode: '09-22',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'ETAH',
            districtNameHindi: 'एटा',
            districtCode: '09-23',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'ETAWAH',
            districtNameHindi: 'इटावा',
            districtCode: '09-24',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'AYODHYA',
            districtNameHindi: 'अयोध्या',
            districtCode: '09-25',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'FARRUKHABAD',
            districtNameHindi: 'फर्रुखाबाद',
            districtCode: '09-26',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'FATEHPUR',
            districtNameHindi: 'फतेहपुर',
            districtCode: '09-27',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'FIROZABAD',
            districtNameHindi: 'फिरोजाबाद',
            districtCode: '09-28',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'GAUTAM BUDDHA NAGAR',
            districtNameHindi: 'गौतम बुद्ध नगर',
            districtCode: '09-29',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'GHAZIABAD',
            districtNameHindi: 'गाजियाबाद',
            districtCode: '09-30',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'GHAZIPUR',
            districtNameHindi: 'गाजीपुर',
            districtCode: '09-31',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'GONDA',
            districtNameHindi: 'गोंडा',
            districtCode: '09-32',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'GORAKHPUR',
            districtNameHindi: 'गोरखपुर',
            districtCode: '09-33',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'HAMIRPUR',
            districtNameHindi: 'हमीरपुर',
            districtCode: '09-34',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'HAPUR',
            districtNameHindi: 'हापुड़',
            districtCode: '09-35',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'HARDOI',
            districtNameHindi: 'हरदोई',
            districtCode: '09-36',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'HATHRAS',
            districtNameHindi: 'हाथरस',
            districtCode: '09-37',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'JALAUN',
            districtNameHindi: 'जालौन',
            districtCode: '09-38',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'JAUNPUR',
            districtNameHindi: 'जौनपुर',
            districtCode: '09-39',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'JHANSI',
            districtNameHindi: 'झांसी',
            districtCode: '09-40',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'KANNAUJ',
            districtNameHindi: 'कन्नौज',
            districtCode: '09-41',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'KANPUR DEHAT',
            districtNameHindi: 'कानपुर देहात',
            districtCode: '09-42',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'KANPUR NAGAR',
            districtNameHindi: 'कानपुर नगर',
            districtCode: '09-43',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'KASGANJ',
            districtNameHindi: 'कासगंज',
            districtCode: '09-44',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'KAUSHAMBI',
            districtNameHindi: 'कौशाम्बी',
            districtCode: '09-45',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'KHERI',
            districtNameHindi: 'खेरी',
            districtCode: '09-46',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'KUSHINAGAR',
            districtNameHindi: 'कुशीनगर',
            districtCode: '09-47',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'LALITPUR',
            districtNameHindi: 'ललितपुर',
            districtCode: '09-48',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'LUCKNOW',
            districtNameHindi: 'लखनऊ',
            districtCode: '09-49',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'MAHARAJGANJ',
            districtNameHindi: 'महाराजगंज',
            districtCode: '09-50',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'MAHOBA',
            districtNameHindi: 'महोबा',
            districtCode: '09-51',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'MAINPURI',
            districtNameHindi: 'मैनपुरी',
            districtCode: '09-52',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'MATHURA',
            districtNameHindi: 'मथुरा',
            districtCode: '09-53',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'MAU',
            districtNameHindi: 'मऊ',
            districtCode: '09-54',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'MEERUT',
            districtNameHindi: 'मेरठ',
            districtCode: '09-55',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'MIRZAPUR',
            districtNameHindi: 'मिर्जापुर',
            districtCode: '09-56',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'MORADABAD',
            districtNameHindi: 'मुरादाबाद',
            districtCode: '09-57',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'MUZAFFARNAGAR',
            districtNameHindi: 'मुजफ्फरनगर',
            districtCode: '09-58',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'PILIBHIT',
            districtNameHindi: 'पीलीभीत',
            districtCode: '09-59',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'PRATAPGARH',
            districtNameHindi: 'प्रतापगढ़',
            districtCode: '09-60',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'PRAYAGRAJ',
            districtNameHindi: 'प्रयागराज',
            districtCode: '09-61',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'RAE BARELI',
            districtNameHindi: 'रायबरेली',
            districtCode: '09-62',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'RAMPUR',
            districtNameHindi: 'रामपुर',
            districtCode: '09-63',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'SAHARANPUR',
            districtNameHindi: 'सहारनपुर',
            districtCode: '09-64',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'SAMBHAL',
            districtNameHindi: 'संभल',
            districtCode: '09-65',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'SANT KABIR NAGAR',
            districtNameHindi: 'संत कबीर नगर',
            districtCode: '09-66',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'SHAHJAHANPUR',
            districtNameHindi: 'शाहजहांपुर',
            districtCode: '09-67',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'SHAMLI',
            districtNameHindi: 'शामली',
            districtCode: '09-68',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'SHRAVASTI',
            districtNameHindi: 'श्रावस्ती',
            districtCode: '09-69',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'SIDDHARTHNAGAR',
            districtNameHindi: 'सिद्धार्थनगर',
            districtCode: '09-70',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'SITAPUR',
            districtNameHindi: 'सीतापुर',
            districtCode: '09-71',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'SONBHADRA',
            districtNameHindi: 'सोनभद्र',
            districtCode: '09-72',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'SULTANPUR',
            districtNameHindi: 'सुल्तानपुर',
            districtCode: '09-73',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'UNNAO',
            districtNameHindi: 'उन्नाव',
            districtCode: '09-74',
            createdAt: timestamp,
        },
        {
            stateName: 'UTTAR PRADESH',
            districtName: 'VARANASI',
            districtNameHindi: 'वाराणसी',
            districtCode: '09-75',
            createdAt: timestamp,
        },
    ];

    await db.insert(districts).values(sampleDistricts);
    
    console.log('✅ Districts seeder completed successfully - 75 UP districts inserted');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});